library(tm)
library(textclean)
library(data.table)
library(flexdashboard)
library(rvest)
library(googlesheets)
library(dplyr)
library(raster)
library(data.table)
library(tools)
library(httr)
library(janitor)
library(tidytext)
library(tidyr)
library(stringr)
library(vwr)
library(datasets)
library(utf8)
install.packages("taskscheduleR", repos = "http://www.datatailor.be/rcube", type = "source")
##Rscript --no-save --no-restore /Users/mbrownsword/debate_one.R 

url_debate_one <- "https://www.washingtonpost.com/politics/2019/06/27/transcript-night-one-first-democratic-debate-annotated/?utm_term=.b5a3c965ea7d&tid=sm_tw"
webpage_debate_one <- read_html(url_debate_one)
debate_one<- webpage_debate_one %>% html_nodes(xpath='//p[@data-elm-loc]') %>% html_text()
write.csv(debate_one,"debate_one.csv")
quit(save="no")
